// Generated by CoffeeScript 1.6.3
(function() {
  define(['js/randomizer'], function(randomizer) {
    return describe("Randomizerをコールする場合", function() {
      beforeEach(function() {
        return this.addMatchers({
          toBeNumber: function() {
            var actual;
            actual = String(this.actual);
            return actual.match(/^[0-9]+$/);
          }
        });
      });
      return it("#数字を返却する", function() {
        var actual, random;
        random = new randomizer();
        actual = random.generate();
        return expect(actual).toBeNumber();
      });
    });
  });

}).call(this);
