// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var note;
    return note = function(title, content) {
      this.title = title;
      return this.content = content;
    };
  });

}).call(this);
