// Generated by CoffeeScript 1.6.3
(function() {
  define(['js/randomizer'], function() {
    var Randomize;
    return Randomize = (function() {
      function Randomize() {}

      Randomize.prototype.generate = function() {
        return Math.floor(Math.random() * 100);
      };

      return Randomize;

    })();
  });

}).call(this);
