// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'underscore'], function($) {
    $(function() {
      $("#testbutton").click(function() {
        return alert(1);
      });
    });
  });

}).call(this);
