// Generated by CoffeeScript 1.6.3
(function() {
  define(['js/notepad'], function(notepad) {
    return describe("returns titles", function() {
      return it("returns titles", function() {
        return expect(notepad.noteTitles()).toEqual("pick up the kids get milk ");
      });
    });
  });

}).call(this);
